export const profileList = [
  {
    name: "Fernando Pereira",
    jobTitle: "Gerente de Projeto",
    section: "programming",
    sectionTitle: "Programação",
  },
  {
    name: "Mariana Gomes",
    jobTitle: "Desenvolvedor Júnior",
    section: "programming",
    sectionTitle: "Programação",
  },
  {
    name: "Pedro Santos",
    jobTitle: "Designer UI",
    section: "front-end",
    sectionTitle: "Front End",
  },
  {
    name: "Bruna Alves",
    jobTitle: "Desenvolvedor Sênior",
    section: "front-end",
    sectionTitle: "Front End",
  },
  {
    name: "Luciana Souza",
    jobTitle: "Analista de Segurança",
    section: "data-science",
    sectionTitle: "Data Science",
  },
  {
    name: "Carla Rodrigues",
    jobTitle: "Especialista em Dados",
    section: "data-science",
    sectionTitle: "Data Science",
  },
  {
    name: "Ana Oliveira",
    jobTitle: "Engenheiro de Cloud",
    section: "devops",
    sectionTitle: "Devops",
  },
  {
    name: "Fernando Pereira",
    jobTitle: "Analista de Qualidade",
    section: "devops",
    sectionTitle: "Devops",
  },
  {
    name: "Leonardo Castro",
    jobTitle: "Designer UX",
    section: "ux-design",
    sectionTitle: "UX e Design",
  },
  {
    name: "Luiz Felipe",
    jobTitle: "Desenvolvedor Júnior",
    section: "ux-design",
    sectionTitle: "UX e Design",
  },
  {
    name: "Carla Rodrigues",
    jobTitle: "Desenvolvedor Pleno",
    section: "mobile",
    sectionTitle: "Mobile",
  },
  {
    name: "Pedro Santos",
    jobTitle: "Gerente de Projeto",
    section: "mobile",
    sectionTitle: "Mobile",
  },
  {
    name: "Bruna Alves",
    jobTitle: "Especialista em Dados",
    section: "innovation-management",
    sectionTitle: "Inovação e Gestão",
  },
  {
    name: "Mariana Gomes",
    jobTitle: "Desenvolvedor Sênior",
    section: "innovation-management",
    sectionTitle: "Inovação e Gestão",
  },
  {
    name: "Leonardo Castro",
    jobTitle: "Desenvolvedor Júnior",
    section: "programming",
    sectionTitle: "Programação",
  },
  {
    name: "Luiz Felipe",
    jobTitle: "Desenvolvedor Pleno",
    section: "programming",
    sectionTitle: "Programação",
  },
  {
    name: "Ana Oliveira",
    jobTitle: "Analista de Qualidade",
    section: "front-end",
    sectionTitle: "Front End",
  },
  {
    name: "Mariana Gomes",
    jobTitle: "Desenvolvedor Pleno",
    section: "front-end",
    sectionTitle: "Front End",
  },
  {
    name: "Carla Rodrigues",
    jobTitle: "Engenheiro de Cloud",
    section: "data-science",
    sectionTitle: "Data Science",
  },
  {
    name: "Fernando Pereira",
    jobTitle: "Designer UI",
    section: "data-science",
    sectionTitle: "Data Science",
  },
  {
    name: "Pedro Santos",
    jobTitle: "Gerente de Projeto",
    section: "devops",
    sectionTitle: "Devops",
  },
  {
    name: "Luciana Souza",
    jobTitle: "Analista de Segurança",
    section: "devops",
    sectionTitle: "Devops",
  },
];
