export const sectionsList = [
  {
    id: "cadastro",
    title: "Cadastro",
    brightColor: "#B4BEFB",
    color: "#6278F7",
    icon: "user-plus",
  },
  {
    id: "programming",
    title: "Programming",
    brightColor: "#D9F7E9",
    color: "#57C278",
    icon: "code",
  },
  {
    id: "front-end",
    title: "Front-end",
    brightColor: "#E8FFFF",
    color: "#82CFFA",
    icon: "desktop",
  },
  {
    id: "data-science",
    title: "Data Science",
    brightColor: "#E9FFE3",
    color: "#A6D157",
    icon: "chart-bar",
  },
  {
    id: "devops",
    title: "DevOps",
    brightColor: "rgba(241, 97, 101, 0.15)",
    color: "#E06B69",
    icon: "server",
  },
  {
    id: "ux-design",
    title: "UX Design",
    brightColor: "rgba(220, 110, 190, 0.15)",
    color: "#DB6EBF",
    icon: "pencil-ruler",
  },
  {
    id: "mobile",
    title: "Mobile",
    brightColor: "rgba(255, 186, 5, 0.15)",
    color: "#FFBA05",
    icon: "mobile-alt",
  },
  {
    id: "innovation-management",
    title: "Innovation Management",
    brightColor: "rgba(255, 140, 42, 0.15)",
    color: "#FF8A29",
    icon: "lightbulb",
  },
];
